# Generated by Django 3.2.11 on 2022-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
