# Generated by Django 3.2.11 on 2022-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupDB',
            fields=[
                ('meet_board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('meet_image_path', models.TextField()),
                ('meet_regi_date', models.DateField()),
            ],
            options={
                'db_table': 'meetup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeDB',
            fields=[
                ('info_board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('info_regi_date', models.DateField()),
            ],
            options={
                'db_table': 'info_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProudDB',
            fields=[
                ('proud_board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('proud_image_path', models.TextField()),
                ('proud_regi_date', models.DateField()),
            ],
            options={
                'db_table': 'proud_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyDB',
            fields=[
                ('study_board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('link_url', models.TextField()),
                ('study_regi_date', models.DateField()),
            ],
            options={
                'db_table': 'study_board',
                'managed': False,
            },
        ),
    ]
